### ISSUE TITLE
Can't see anything in unstaking interface

### ISSUE THREAD

**Issue by susanneetherisc** [etherisc/staking-ui#120]
### What happened?

A bug spotted by hbos#4623, I can also see the same issue

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Safari

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
only bundles which are not active (closed, expired, burnt) can be unstaked.
