### ISSUE TITLE
Can't see duration of staking bundle in staking interface

### ISSUE THREAD

**Issue by susanneetherisc** [etherisc/staking-ui#121]
### What happened?

A bug spotted by hbos#4623 - I see the same bug

### What operating system are you seeing the problem on?

Mac OS

### What browsers are you seeing the problem on?

Safari

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
would be a good idea to show the bundle expiration. will see if i can get the data in the staking context.

**Comment by susanneetherisc** [comment]
Waiting for wallet address have contacted hbos

**Comment by susanneetherisc** [comment]
Have chased several times but doesn't seem keen to claim bounty / worried about sharing wallet address
