### ISSUE TITLE
[Bug]: Inconsistency in between  "Stake DIP" and "Unstake DIP" views 

### ISSUE THREAD

**Issue by rapidddenis** [etherisc/staking-ui#138]
### What happened?

"Unstake DIP" is not showing all the bundles seen in "Stake DIP" if any.
 
<img width="1726" alt="Screenshot 2023-02-28 at 11 52 50" src="https://user-images.githubusercontent.com/41779817/221923452-75a84ce9-ccd4-43e9-8137-b5d3e25afd3c.png">

<img width="1726" alt="Screenshot 2023-02-28 at 11 52 30" src="https://user-images.githubusercontent.com/41779817/221923534-3fefae05-52f8-4afa-ab7a-2c2a1f7c2b9d.png">

### What operating system are you seeing the problem on?

Mac OS

### What browsers are you seeing the problem on?

Firefox

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
Unstaking is only possible on bundles which are expired, closed or burned and the action will also only show if the active wallet has staked a bundle. 

We will include a note on the page mentioning this to make it clear -> https://github.com/etherisc/staking-ui/issues/137

Also there is an issue with the bundle state not being updated correctly in the bundle registry when changed in depeg (but the functions for lock/unlock/close/burn are not available yet, but will be soon).
