### ISSUE TITLE
[Bug]: Claim rewards button is available even if user have no accumulated rewards

### ISSUE THREAD

**Issue by rapidddenis** [etherisc/staking-ui#176]
### What happened?

<img width="944" alt="Screenshot 2023-03-14 at 17 11 14" src="https://user-images.githubusercontent.com/41779817/225137573-9b27aa4f-9ca1-44d9-9c94-84b916bd9943.png">

Also unclear what the field "Accumulated Rewards" shows? All/user's    rewards    since bundle creation/available to withdraw.

### What operating system are you seeing the problem on?

Mac OS

### What browsers are you seeing the problem on?

Firefox

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
showing amount as `< 0.01` is very small reward is claimable.
