### ISSUE TITLE
[Bug]: Low contrast between font color and background color

### ISSUE THREAD

**Issue by gebunu** [etherisc/staking-ui#77]
### What happened?

Some observations:

Low contrast between font color and background color render text it a bit hard to read
Small typo under "Expected rewards" text where it reads "Please not, {...}" instead of Please note
End of bundle lifetime date not clear when staking

### What operating system are you seeing the problem on?

Windows

### What browsers are you seeing the problem on?

Firefox

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
The `Please not` text was already fixed, but not pushed to the server. Will be there with the next update.

**Comment by doerfli** [comment]
Using the 800 or 900 colors from material design works well in terms of contrast.

**Comment by susanneetherisc** [comment]
Bounty paid

**Comment by doerfli** [comment]
new color scheme should improve contrast.
