### ISSUE TITLE
[Bug]: Unstake not showing bundles 

### ISSUE THREAD

**Issue by 1Eskor** [etherisc/staking-ui#82]
### What happened?

I like it so far. I was able to get the test DIP/MATIC successfully, and staked some tokens and confirmed the transaction. Going to unstake it did not show my bundles (or any) .. I thought maybe this was because of a minimum amount of time that needed to be locked, but there was no information/clickable link to the terms & conditions..  I dunno if that is a bug or intentional.. But overall I do like the application. Also it might be beneficial to publish the smart contract to test its functions. Its impossible to decompile the bytecode. (I understand if there is some hesitance there, but better to find the vulnerabilities on test net imo) .. Excited to see this live 👌👍

(photos) https://docs.google.com/document/d/15Gt80B0TfjF967jy7S9iM5xKoKT72NiReyF_aaQUGcM/edit?usp=sharing

### What operating system are you seeing the problem on?

Mac OS

### What browsers are you seeing the problem on?

Brave

### What wallet extension are you using?

Metamask

### Rules

- [X] I agree to follow this project's rules

**Comment by doerfli** [comment]
Thanks for testing the staking application. But this is not a bug, it works as intended. Unstaking is only available for closed bundles. We could manually close a bundle, but depending if it has policies or not it might be a bit tricky. I will be easier to get a closed bundle once we got payouts ready, which will hopefully be soon. 

Regarding smart contracts, they are available on github too. You can find the smart contracts for the depeg insurance in the repository https://github.com/etherisc/depeg-contracts And the framework code is available at https://github.com/etherisc/gif-interface and https://github.com/etherisc/gif-contracts

**Comment by doerfli** [comment]
And regarding terms and conditions, they're work in progress.
