### ISSUE TITLE
Staking final configuration for min/max amounts, durations, etc

### ISSUE THREAD

**Issue by doerfli** [etherisc/staking-ui#91]
# Current configuration DIP Staking (Mumbai)

- DIP staking minumum:  `10,000` per transaction
- DIP staking maximum: `10,000,000` per transaction
- No maximum cap

@christoph2806 / @matthiaszimmermann please let me know the final values you want to see.

**Comment by doerfli** [comment]
- DIP staking minumum:  `5,000` per transaction
- DIP staking maximum: `10,000,000` per transaction
- No maximum cap

**Comment by matthiaszimmermann** [comment]
checklist completed
